import { describe, it, expect } from 'vitest';
import { createFreematicaServer } from '../src/server.js';
import { FreematicaClient } from '../src/clients/freematica-client.js';

const TEST_CLIENT = new FreematicaClient({
  baseUrl: 'https://x.example.com',
  authHeaders: {
    'x-auth-token': 't',
    'x-auth-company': 'c',
    'x-auth-organization': 'o',
    'x-auth-app': 'a',
    'x-auth-session': 's',
  },
});

function registeredToolNames(server: ReturnType<typeof createFreematicaServer>): string[] {
  const tools = (server as unknown as { _registeredTools: Record<string, unknown> })._registeredTools;
  return Object.keys(tools).sort();
}

const READ_ONLY_TOOLS = [
  'freematica_export_asientos',
  'freematica_get_albaran_factura',
  'freematica_get_albaran_venta',
  'freematica_get_articulo',
  'freematica_get_precio_articulo',
  'freematica_list_articulos',
  'freematica_get_cartera_cliente',
  'freematica_get_cliente',
  'freematica_get_contrato',
  'freematica_get_contrato_opcionales',
  'freematica_get_edicom_info',
  'freematica_get_factura_cabecera',
  'freematica_get_factura_compra',
  'freematica_get_factura_documento',
  'freematica_get_factura_electronica',
  'freematica_get_factura_log',
  'freematica_get_ficha_prev_cliente',
  'freematica_get_master_data',
  'freematica_get_oportunidad_negocio',
  'freematica_get_oportunidad_negocio_datos_ampliados',
  'freematica_get_pedido_compra',
  'freematica_get_persona',
  'freematica_get_proveedor',
  'freematica_get_servicio_contrato',
  'freematica_get_vigilancia_salud',
  'freematica_list_albaranes_factura',
  'freematica_list_albaranes_ventas',
  'freematica_list_calendario_periodos',
  'freematica_list_calendarios',
  'freematica_list_cartera_clientes',
  'freematica_list_clientes',
  'freematica_list_contactos_clientes',
  'freematica_list_contratos',
  'freematica_list_contratos_opcionales',
  'freematica_list_cuentas_analiticas',
  'freematica_list_cuentas_contables',
  'freematica_list_factura_iva',
  'freematica_list_factura_lineas',
  'freematica_list_factura_vencimientos',
  'freematica_list_facturas_cabecera',
  'freematica_list_facturas_compras',
  'freematica_list_facturas_documentos',
  'freematica_list_facturas_electronicas',
  'freematica_list_localizaciones_cobro_clientes',
  'freematica_list_localizaciones_envio_clientes',
  'freematica_list_localizaciones_factura_clientes',
  'freematica_list_localizaciones_pago_proveedores',
  'freematica_list_localizaciones_servicio_clientes',
  'freematica_list_materiales_asignados_servicios',
  'freematica_list_oportunidades_negocio',
  'freematica_list_pedidos_compra',
  'freematica_list_personal',
  'freematica_list_proveedores',
  'freematica_list_servicios_contrato',
  'freematica_list_resultados_facturacion',
  'freematica_list_vigilancia_salud',
  // v0.10.0 — vínculos personas↔servicios
  'freematica_list_vinculos_personas_servicios',
  'freematica_get_vinculo_persona_servicio',
  // v0.10.0 — habilitaciones CAE
  'freematica_list_habilitaciones_servicios_alta',
  'freematica_list_habilitaciones_servicios_baja',
  'freematica_list_habilitaciones_personal_alta',
  'freematica_list_habilitaciones_personal_baja',
  // v0.10.0 — cuadrantes
  'freematica_list_cuadrantes',
  'freematica_list_cuadrantes_detalles',
  'freematica_list_cuadrantes_observaciones',
  'freematica_list_cuadrantes_auditoria',
  'freematica_list_cuadrantes_tareas',
  'freematica_list_computos_pers',
  'freematica_get_computos_pers',
  'freematica_get_computos_pers_h',
  'freematica_list_cuadrantes_cierre_personas',
  'freematica_get_cuadrante_cierre_persona',
  'freematica_list_cuadrantes_cierre_personas_complementos',
  'freematica_get_cuadrante_cierre_persona_complemento',
  'freematica_list_cuadrantes_cierre_personas_especiales',
  'freematica_get_cuadrante_cierre_persona_especial',
  'freematica_list_cuadrantes_cierre_personas_incidencias',
  'freematica_get_cuadrante_cierre_persona_incidencia',
  // v0.10.0 — servicios PVSS extras
  'freematica_list_contratos_servicios_global',
  'freematica_list_contratos_turnos',
  'freematica_list_contratos_horarios_operativa',
  'freematica_list_clases_servicios',
  'freematica_list_inspectores',
  'freematica_get_inspector_empresa',
  'freematica_list_claves_facturacion',
  'freematica_list_incidencias_servicios',
  'freematica_get_incidencia_servicio',
  'freematica_list_incidencecode',
  'freematica_get_contratos_servicios_material',
  // personal-ext read tools
  'freematica_list_personal_v2',
  'freematica_list_personal_identificacion',
  'freematica_list_personal_notas',
  'freematica_get_personal_nota',
  'freematica_list_personal_experiencias',
  'freematica_get_personal_experiencia',
  'freematica_list_personal_formaciones',
  'freematica_get_personal_formacion',
  'freematica_list_personal_contratos',
  'freematica_get_personal_contrato',
  'freematica_list_personal_tramos',
  'freematica_get_personal_tramo',
  'freematica_list_personal_tramos_sync',
  'freematica_get_personal_tramo_v2',
  'freematica_list_personal_pago',
  'freematica_get_personal_pago',
  'freematica_list_personal_adicionales',
  'freematica_list_personal_prorroga',
  'freematica_get_personal_prorroga',
  'freematica_list_incidencias_personal',
  'freematica_get_agenda_persona',
  'freematica_list_equipamiento_ficha_seguridad',
  'freematica_list_anticipos_personal',
  'freematica_get_anticipo_personal',
  'freematica_list_calendario_personal',
  'freematica_get_calendario_personal',
  'freematica_list_cpd',
  'freematica_get_cpd',
  'freematica_list_cpd_movimientos',
  'freematica_list_cpd_firmados_vid',
  'freematica_list_personal_irpf',
  'freematica_get_personal_irpf',
  'freematica_list_sesiones_formacion',
  'freematica_get_sesion_formacion',
  'freematica_list_vss_incidencias',
  'freematica_get_vss_incidencia',
  // ppre — Preventivos / Mantenimiento / Instalaciones
  'freematica_list_ppre_contratos',
  'freematica_list_ppre_contratos_v2',
  'freematica_get_ppre_contrato_v1',
  'freematica_get_ppre_contrato_v2',
  'freematica_list_ppre_contratos_instalacion',
  'freematica_list_ppre_tipos_contrato',
  'freematica_list_ppre_ordenes_trabajo',
  'freematica_get_ppre_orden_trabajo',
  'freematica_list_ppre_partes',
  'freematica_get_ppre_parte',
  'freematica_get_ppre_parte_componentes_ficha_tecnica',
  'freematica_list_ppre_parte_ultimas_intervenciones',
  'freematica_list_ppre_partes_orden_trabajo',
  'freematica_list_ppre_partes_fin_mantenedor',
  'freematica_list_ppre_cabecera_actas_partes',
  'freematica_list_ppre_lineas_actas_partes',
  'freematica_list_ppre_fichas_instalacion',
  'freematica_get_ppre_ficha_tecnica',
  'freematica_list_ppre_componentes_ficha_tecnica',
  'freematica_list_ppre_marcajes',
  'freematica_list_ppre_marcajes_v2',
  'freematica_list_ppre_incidencias_anomalias',
  'freematica_list_ppre_tipo_instalacion',
].sort();

const WRITE_TOOLS = [
  'freematica_create_cliente',
  'freematica_create_contacto_cliente',
  'freematica_create_localizacion_cliente',
  'freematica_create_contrato',
  'freematica_create_contrato_opcionales',
  'freematica_create_servicio_contrato',
  'freematica_create_servicio_facturacion_txt',
  'freematica_create_servicio_historico_precios',
  'freematica_update_cliente',
  'freematica_update_contacto_cliente',
  'freematica_update_localizacion_cliente',
  'freematica_update_contrato',
  'freematica_update_contrato_opcionales',
  'freematica_update_servicio_facturacion',
  'freematica_update_servicio_fechas',
  'freematica_update_servicio_historico_precios',
  // personal-ext write tools
  'freematica_create_persona',
  'freematica_update_persona',
  'freematica_create_personal_identificacion',
  'freematica_create_personal_nota',
  'freematica_update_personal_nota',
  'freematica_create_personal_experiencia',
  'freematica_create_personal_formacion',
  'freematica_update_personal_formacion',
  'freematica_create_incidencia_base',
  'freematica_update_incidencia_base_fecha_fin',
  'freematica_create_personal_pago',
  'freematica_update_personal_pago',
  'freematica_create_personal_tramo',
  'freematica_update_personal_tramo',
  'freematica_create_personal_contrato',
  'freematica_update_personal_contrato',
  'freematica_create_personal_adicional',
  'freematica_update_personal_adicional',
  'freematica_create_anticipo_personal',
  'freematica_create_calendario_personal',
  'freematica_update_calendario_personal',
  'freematica_update_cpd_bulk',
  'freematica_update_cpd_gestion',
  'freematica_create_personal_irpf',
  'freematica_update_personal_irpf',
  'freematica_create_personal_irpf_ad',
  'freematica_update_personal_irpf_ad',
  'freematica_update_preventor',
  'freematica_update_preventor_estado',
  // ppre write tools
  'freematica_create_ppre_contrato',
  'freematica_create_ppre_orden_trabajo',
  'freematica_update_ppre_orden_trabajo',
  'freematica_update_ppre_lineas_actas_partes',
  'freematica_create_ppre_ficha_instalacion_material',
  'freematica_update_ppre_ficha_instalacion',
  'freematica_create_ppre_marcaje',
  'freematica_update_ppre_marcaje_v1',
  'freematica_update_ppre_marcaje_v2',
].sort();

describe('createFreematicaServer', () => {
  it('registers all expected read-only tools by default', () => {
    const server = createFreematicaServer({ client: TEST_CLIENT });
    const names = registeredToolNames(server);
    expect(names).toEqual(READ_ONLY_TOOLS);
  });

  it('registers all write tools only with enableWrites=true', () => {
    const server = createFreematicaServer({ client: TEST_CLIENT, enableWrites: true });
    const names = registeredToolNames(server);
    expect(names).toEqual([...READ_ONLY_TOOLS, ...WRITE_TOOLS].sort());
  });

  it('never registers delete tools', () => {
    const server = createFreematicaServer({ client: TEST_CLIENT, enableWrites: true });
    const names = registeredToolNames(server);
    expect(names.filter((n) => n.includes('delete'))).toEqual([]);
  });
});
