import { describe, it, expect } from 'vitest';
import { createFreematicaServer } from '../src/server.js';
import { FreematicaClient } from '../src/clients/freematica-client.js';

const TEST_CLIENT = new FreematicaClient({
  baseUrl: 'https://x.example.com',
  authHeaders: {
    'x-auth-token': 't',
    'x-auth-company': 'c',
    'x-auth-organization': 'o',
    'x-auth-app': 'a',
    'x-auth-session': 's',
  },
});

function registeredToolNames(server: ReturnType<typeof createFreematicaServer>): string[] {
  const tools = (server as unknown as { _registeredTools: Record<string, unknown> })._registeredTools;
  return Object.keys(tools).sort();
}

const READ_ONLY_TOOLS = [
  'freematica_export_asientos',
  'freematica_get_albaran_factura',
  'freematica_get_albaran_venta',
  'freematica_get_articulo',
  'freematica_get_precio_articulo',
  'freematica_list_articulos',
  'freematica_get_cartera_cliente',
  'freematica_get_cliente',
  'freematica_get_contrato',
  'freematica_get_contrato_opcionales',
  'freematica_get_edicom_info',
  'freematica_get_factura_cabecera',
  'freematica_get_factura_compra',
  'freematica_get_factura_documento',
  'freematica_get_factura_electronica',
  'freematica_get_factura_log',
  'freematica_get_ficha_prev_cliente',
  'freematica_get_master_data',
  'freematica_get_oportunidad_negocio',
  'freematica_get_oportunidad_negocio_datos_ampliados',
  'freematica_get_pedido_compra',
  'freematica_get_persona',
  'freematica_get_proveedor',
  'freematica_get_servicio_contrato',
  'freematica_get_vigilancia_salud',
  'freematica_list_albaranes_factura',
  'freematica_list_albaranes_ventas',
  'freematica_list_calendario_periodos',
  'freematica_list_calendarios',
  'freematica_list_cartera_clientes',
  'freematica_list_clientes',
  'freematica_list_contactos_clientes',
  'freematica_list_contratos',
  'freematica_list_contratos_opcionales',
  'freematica_list_cuentas_analiticas',
  'freematica_list_cuentas_contables',
  'freematica_list_factura_iva',
  'freematica_list_factura_lineas',
  'freematica_list_factura_vencimientos',
  'freematica_list_facturas_cabecera',
  'freematica_list_facturas_compras',
  'freematica_list_facturas_documentos',
  'freematica_list_facturas_electronicas',
  'freematica_list_localizaciones_cobro_clientes',
  'freematica_list_localizaciones_envio_clientes',
  'freematica_list_localizaciones_factura_clientes',
  'freematica_list_localizaciones_pago_proveedores',
  'freematica_list_localizaciones_servicio_clientes',
  'freematica_list_materiales_asignados_servicios',
  'freematica_list_oportunidades_negocio',
  'freematica_list_pedidos_compra',
  'freematica_list_personal',
  'freematica_list_proveedores',
  'freematica_list_servicios_contrato',
  'freematica_list_resultados_facturacion',
  'freematica_list_vigilancia_salud',
  // v0.10.0 — vínculos personas↔servicios
  'freematica_list_vinculos_personas_servicios',
  'freematica_get_vinculo_persona_servicio',
  // v0.10.0 — habilitaciones CAE
  'freematica_list_habilitaciones_servicios_alta',
  'freematica_list_habilitaciones_servicios_baja',
  'freematica_list_habilitaciones_personal_alta',
  'freematica_list_habilitaciones_personal_baja',
  // v0.10.0 — cuadrantes
  'freematica_list_cuadrantes',
  'freematica_list_cuadrantes_detalles',
  'freematica_list_cuadrantes_observaciones',
  'freematica_list_cuadrantes_auditoria',
  'freematica_list_cuadrantes_tareas',
  'freematica_list_computos_pers',
  'freematica_get_computos_pers',
  'freematica_get_computos_pers_h',
  'freematica_list_cuadrantes_cierre_personas',
  'freematica_get_cuadrante_cierre_persona',
  'freematica_list_cuadrantes_cierre_personas_complementos',
  'freematica_get_cuadrante_cierre_persona_complemento',
  'freematica_list_cuadrantes_cierre_personas_especiales',
  'freematica_get_cuadrante_cierre_persona_especial',
  'freematica_list_cuadrantes_cierre_personas_incidencias',
  'freematica_get_cuadrante_cierre_persona_incidencia',
  // v0.10.0 — servicios PVSS extras
  'freematica_list_contratos_servicios_global',
  'freematica_list_contratos_turnos',
  'freematica_list_contratos_horarios_operativa',
  'freematica_list_clases_servicios',
  'freematica_list_inspectores',
  'freematica_get_inspector_empresa',
  'freematica_list_claves_facturacion',
  'freematica_list_incidencias_servicios',
  'freematica_get_incidencia_servicio',
  'freematica_list_incidencecode',
  'freematica_get_contratos_servicios_material',
  // personal-ext read tools
  'freematica_list_personal_v2',
  'freematica_list_personal_identificacion',
  'freematica_list_personal_notas',
  'freematica_get_personal_nota',
  'freematica_list_personal_experiencias',
  'freematica_get_personal_experiencia',
  'freematica_list_personal_formaciones',
  'freematica_get_personal_formacion',
  'freematica_list_personal_contratos',
  'freematica_get_personal_contrato',
  'freematica_list_personal_tramos',
  'freematica_get_personal_tramo',
  'freematica_list_personal_tramos_sync',
  'freematica_get_personal_tramo_v2',
  'freematica_list_personal_pago',
  'freematica_get_personal_pago',
  'freematica_list_personal_adicionales',
  'freematica_list_personal_prorroga',
  'freematica_get_personal_prorroga',
  'freematica_list_incidencias_personal',
  'freematica_get_agenda_persona',
  'freematica_list_equipamiento_ficha_seguridad',
  'freematica_list_anticipos_personal',
  'freematica_get_anticipo_personal',
  'freematica_list_calendario_personal',
  'freematica_get_calendario_personal',
  'freematica_list_cpd',
  'freematica_get_cpd',
  'freematica_list_cpd_movimientos',
  'freematica_list_cpd_firmados_vid',
  'freematica_list_personal_irpf',
  'freematica_get_personal_irpf',
  'freematica_list_sesiones_formacion',
  'freematica_get_sesion_formacion',
  'freematica_list_vss_incidencias',
  'freematica_get_vss_incidencia',
  // ppre — Preventivos / Mantenimiento / Instalaciones
  'freematica_list_ppre_contratos',
  'freematica_list_ppre_contratos_v2',
  'freematica_get_ppre_contrato_v1',
  'freematica_get_ppre_contrato_v2',
  'freematica_list_ppre_contratos_instalacion',
  'freematica_list_ppre_tipos_contrato',
  'freematica_list_ppre_ordenes_trabajo',
  'freematica_get_ppre_orden_trabajo',
  'freematica_list_ppre_partes',
  'freematica_get_ppre_parte',
  'freematica_get_ppre_parte_componentes_ficha_tecnica',
  'freematica_list_ppre_parte_ultimas_intervenciones',
  'freematica_list_ppre_partes_orden_trabajo',
  'freematica_list_ppre_partes_fin_mantenedor',
  'freematica_list_ppre_cabecera_actas_partes',
  'freematica_list_ppre_lineas_actas_partes',
  'freematica_list_ppre_fichas_instalacion',
  'freematica_get_ppre_ficha_tecnica',
  'freematica_list_ppre_componentes_ficha_tecnica',
  'freematica_list_ppre_marcajes',
  'freematica_list_ppre_marcajes_v2',
  'freematica_list_ppre_incidencias_anomalias',
  'freematica_list_ppre_tipo_instalacion',
  // pemf — e-Movifree / Operativa de Campo
  'freematica_list_pemf_marcajes',
  'freematica_get_pemf_marcaje',
  'freematica_list_pemf_tracking',
  'freematica_list_pemf_calls',
  'freematica_list_pemf_geoposition',
  'freematica_list_pemf_geoposition_v2',
  'freematica_list_pemf_cna',
  'freematica_list_pemf_devices',
  'freematica_get_pemf_device',
  'freematica_list_pemf_rondas',
  'freematica_list_pemf_rondas_v2',
  'freematica_list_pemf_ronda_points',
  'freematica_list_pemf_ronda_points_v2',
  'freematica_list_pemf_services',
  'freematica_get_pemf_service',
  'freematica_list_pemf_service_alarms',
  'freematica_list_pemf_service_issues',
  'freematica_list_pemf_service_rounds',
  'freematica_list_pemf_service_jobs',
  'freematica_list_pemf_identificadores_servicio',
  'freematica_list_pemf_rutas',
  'freematica_list_pemf_materiales_consumibles',
  'freematica_list_pemf_materiales_imputados',
  'freematica_get_pemf_config_global',
  'freematica_get_pemf_config',
  'freematica_list_pemf_usuarios_notificaciones',
  'freematica_get_pemf_operario',
  'freematica_list_pemf_descubiertos',
  // pcrm — CRM extendido (Fase 4)
  'freematica_list_pcrm_actividades',
  'freematica_get_pcrm_actividad',
  'freematica_list_pcrm_casos',
  'freematica_get_pcrm_caso',
  'freematica_list_pcrm_tipos_casos',
  'freematica_get_pcrm_tipo_caso',
  'freematica_list_pcrm_subtipos_casos',
  'freematica_get_pcrm_subtipo_caso',
  'freematica_list_pcrm_documentos_usuario_v1',
  'freematica_get_pcrm_documento_usuario_v1',
  'freematica_list_pcrm_documentos_usuario_v2',
  'freematica_get_pcrm_documento_usuario_v2',
  'freematica_list_pcrm_notas',
  'freematica_get_pcrm_nota',
  'freematica_get_oportunidad_negocio_v1',
  'freematica_list_tipos_oportunidad_negocio',
  'freematica_get_tipo_oportunidad_negocio',
  // part — Inventario/Artículos (Fase 5)
  'freematica_list_articulos_costes',
  'freematica_get_articulo_coste',
  'freematica_list_articulos_serie_lote',
  'freematica_get_articulo_serie_lote',
  'freematica_list_stocks_serie_lote',
  'freematica_get_stock_serie_lote',
  'freematica_list_stocks',
  'freematica_get_stock',
  'freematica_list_familias',
  'freematica_get_familia',
  'freematica_list_lineas',
  'freematica_get_linea',
  'freematica_list_subfamilias',
  'freematica_get_subfamilia',
  // pgrl — completar (clientes v1, contactos v1, localizaciones detalles, catálogos, instaladores, correo, cargos)
  'freematica_list_clientes_v1',
  'freematica_get_cliente_v1',
  'freematica_list_contactos_clientes_v1',
  'freematica_get_contacto_cliente',
  'freematica_list_localizaciones_cobro_clientes_v1',
  'freematica_get_localizacion_cobro_cliente',
  'freematica_get_localizacion_cobro_cliente_v2',
  'freematica_list_localizaciones_envio_clientes_v1',
  'freematica_get_localizacion_envio_cliente',
  'freematica_get_localizacion_envio_cliente_v2',
  'freematica_get_localizacion_factura_cliente',
  'freematica_list_localizaciones_servicio_clientes_v1',
  'freematica_get_localizacion_servicio_cliente',
  'freematica_get_localizacion_servicio_cliente_v2',
  'freematica_list_localizaciones_pago_proveedores_v1',
  'freematica_get_localizacion_pago_proveedor',
  'freematica_get_localizacion_pago_proveedor_v2',
  'freematica_list_proveedores_v1',
  'freematica_list_cargos_clientes',
  'freematica_get_cargo_cliente',
  'freematica_list_calen_festivos',
  'freematica_get_calen_festivo',
  'freematica_list_delegaciones_v1',
  'freematica_get_delegacion_v1',
  'freematica_list_delegaciones_agrupcod',
  'freematica_list_delegaciones_v2',
  'freematica_get_delegacion_v2',
  'freematica_list_empresas',
  'freematica_get_empresa',
  'freematica_list_paises',
  'freematica_list_provincias',
  'freematica_list_nacionalidades',
  'freematica_list_poblaciones',
  'freematica_get_poblacion',
  'freematica_list_series',
  'freematica_list_lineas_negocio',
  'freematica_list_bancos',
  'freematica_list_tipos_impuestos',
  'freematica_get_tipo_impuesto',
  'freematica_list_usuarios_satelite',
  'freematica_get_configuracion_usuario',
  'freematica_list_auditoria_procesos',
  'freematica_list_instaladores',
  'freematica_get_instalador',
  'freematica_get_instalador_stocks',
  'freematica_list_instalador_propuestas_compras',
  'freematica_get_parte_instalacion',
  'freematica_list_correos',
  'freematica_get_correo',
  'freematica_list_correos_destinatarios',
  'freematica_get_correos_totales',
  'freematica_list_correo_v1',
  'freematica_verificar_mail',
  // Fase 7 — nuevas lecturas
  'freematica_list_acompanante_ruta',
  'freematica_list_campos_estadisticos',
  'freematica_list_inspecciones',
  'freematica_list_naturalezas_abono',
  'freematica_list_normas',
  'freematica_list_plantillas',
  'freematica_list_propuestas_compra',
  'freematica_list_rutas_gestion',
  'freematica_list_rutas_planificacion',
  'freematica_get_solicitud_material',
  'freematica_list_solicitudes_material',
].sort();

const WRITE_TOOLS = [
  'freematica_mailing_unsubscribe',
  'freematica_mailing_subscribe',
  'freematica_create_cliente',
  'freematica_create_contacto_cliente',
  'freematica_create_localizacion_cliente',
  'freematica_create_contrato',
  'freematica_create_contrato_opcionales',
  'freematica_create_servicio_contrato',
  'freematica_create_servicio_facturacion_txt',
  'freematica_create_servicio_historico_precios',
  'freematica_update_cliente',
  'freematica_update_contacto_cliente',
  'freematica_update_localizacion_cliente',
  'freematica_update_contrato',
  'freematica_update_contrato_opcionales',
  'freematica_update_servicio_facturacion',
  'freematica_update_servicio_fechas',
  'freematica_update_servicio_historico_precios',
  // personal-ext write tools
  'freematica_create_persona',
  'freematica_update_persona',
  'freematica_create_personal_identificacion',
  'freematica_create_personal_nota',
  'freematica_update_personal_nota',
  'freematica_create_personal_experiencia',
  'freematica_create_personal_formacion',
  'freematica_update_personal_formacion',
  'freematica_create_incidencia_base',
  'freematica_update_incidencia_base_fecha_fin',
  'freematica_create_personal_pago',
  'freematica_update_personal_pago',
  'freematica_create_personal_tramo',
  'freematica_update_personal_tramo',
  'freematica_create_personal_contrato',
  'freematica_update_personal_contrato',
  'freematica_create_personal_adicional',
  'freematica_update_personal_adicional',
  'freematica_create_anticipo_personal',
  'freematica_create_calendario_personal',
  'freematica_update_calendario_personal',
  'freematica_update_cpd_bulk',
  'freematica_update_cpd_gestion',
  'freematica_create_personal_irpf',
  'freematica_update_personal_irpf',
  'freematica_create_personal_irpf_ad',
  'freematica_update_personal_irpf_ad',
  'freematica_update_preventor',
  'freematica_update_preventor_estado',
  // ppre write tools
  'freematica_create_ppre_contrato',
  'freematica_create_ppre_orden_trabajo',
  'freematica_update_ppre_orden_trabajo',
  'freematica_update_ppre_lineas_actas_partes',
  'freematica_create_ppre_ficha_instalacion_material',
  'freematica_update_ppre_ficha_instalacion',
  'freematica_create_ppre_marcaje',
  'freematica_update_ppre_marcaje_v1',
  'freematica_update_ppre_marcaje_v2',
  // pemf write tools
  'freematica_create_pemf_marcaje',
  'freematica_create_pemf_marcaje_fecha_persona',
  'freematica_create_pemf_device',
  'freematica_update_pemf_device',
  'freematica_create_pemf_ronda',
  'freematica_save_pemf_config',
  'freematica_update_pemf_config',
  'freematica_update_pemf_ruta',
  // pcrm write tools (Fase 4)
  'freematica_create_pcrm_actividad',
  'freematica_update_pcrm_actividad',
  'freematica_create_pcrm_caso',
  'freematica_update_pcrm_caso',
  'freematica_update_pcrm_documento_usuario_v1',
  'freematica_update_pcrm_documento_usuario_v2',
  'freematica_create_pcrm_nota',
  'freematica_create_oportunidad_negocio_v1',
  'freematica_create_oportunidad_negocio',
  'freematica_update_oportunidad_negocio_v1',
  'freematica_update_oportunidad_negocio',
  'freematica_update_oportunidad_negocio_datos_ampliados',
  // part write tools (Fase 5)
  'freematica_create_articulo',
  'freematica_update_articulo',
  'freematica_create_articulo_serie_lote',
  'freematica_create_movimiento_stock',
  'freematica_create_entrada_produccion',
  'freematica_create_albaran_traspaso',
  'freematica_traspaso_albaran',
  // pgrl — completar write tools
  'freematica_create_proveedor',
  'freematica_update_proveedor',
  'freematica_create_localizacion_pago_proveedor',
  'freematica_update_localizacion_pago_proveedor',
  'freematica_create_calen_festivo',
  'freematica_update_calen_festivo',
  'freematica_update_calen_festivo_det',
  'freematica_create_instalador_propuesta_compra',
  'freematica_create_correo_v1',
  'freematica_create_correo',
  'freematica_update_correo_estado_v1',
  'freematica_update_correo_estado',
  // Fase 7 — nuevas escrituras
  'freematica_actualizar_alta_habilitaciones_personal',
  'freematica_actualizar_alta_habilitaciones_servicios',
  'freematica_actualizar_baja_habilitaciones_personal',
  'freematica_actualizar_baja_habilitaciones_servicios',
  'freematica_create_albaran_venta',
  'freematica_create_campo_estadistico',
  'freematica_create_computo_pers',
  'freematica_create_computo_pers_h',
  'freematica_create_factura_estado',
  'freematica_create_informe_control',
  'freematica_create_propuesta_compra',
  'freematica_create_solicitud_material',
  'freematica_import_asientos',
  'freematica_recibir_pedido',
  'freematica_update_albaran_fch_traspaso_ext',
  'freematica_update_campo_estadistico',
  'freematica_update_computo_pers',
  'freematica_update_cuadrante',
  'freematica_update_factura_compra',
  'freematica_update_factura_electronica_v1',
  'freematica_update_factura_electronica_v2',
  'freematica_update_factura_leido',
  'freematica_update_pedido_fechas',
  'freematica_update_servicio_fch_fin',
].sort();

describe('createFreematicaServer', () => {
  it('registers all expected read-only tools by default', () => {
    const server = createFreematicaServer({ client: TEST_CLIENT });
    const names = registeredToolNames(server);
    expect(names).toEqual(READ_ONLY_TOOLS);
  });

  it('registers all write tools only with enableWrites=true', () => {
    const server = createFreematicaServer({ client: TEST_CLIENT, enableWrites: true });
    const names = registeredToolNames(server);
    expect(names).toEqual([...READ_ONLY_TOOLS, ...WRITE_TOOLS].sort());
  });

  it('never registers delete tools', () => {
    const server = createFreematicaServer({ client: TEST_CLIENT, enableWrites: true });
    const names = registeredToolNames(server);
    expect(names.filter((n) => n.includes('delete'))).toEqual([]);
  });
});
